export const mockUsers = [
	{
		id: 1,
		username: 'gwawer0',
		first_name: 'Glad',
		last_name: 'Wawer',
		profile_image:
			'https://robohash.org/utvoluptatemveritatis.png?size=50x50&set=set1',
		email: 'gwawer0@cbslocal.com',
		gender: 'Male',
		city: 'Tanjiaqiao',
		country: 'China',
		ethnicity: 'Chinese',
		cuisine: 'Iroquois food',
		interests: 'Playing Instruments',
	},
	{
		id: 2,
		username: 'teatherton1',
		first_name: 'Tadeo',
		last_name: 'Eatherton',
		profile_image:
			'https://robohash.org/repellatmolestiaedicta.png?size=50x50&set=set1',
		email: 'teatherton1@slideshare.net',
		gender: 'Bigender',
		city: 'Shingū',
		country: 'Japan',
		ethnicity: 'Sri Lankan',
		cuisine: 'Honduran food',
		interests: 'Video Games',
	},
	{
		id: 3,
		username: 'rzupo2',
		first_name: 'Rosco',
		last_name: 'Zupo',
		profile_image: 'https://robohash.org/maximeeumet.png?size=50x50&set=set1',
		email: 'rzupo2@geocities.jp',
		gender: 'Female',
		city: 'Uwajima',
		country: 'Japan',
		ethnicity: 'Taiwanese',
		cuisine: 'Chamorro food',
		interests: 'Music',
	},
	{
		id: 4,
		username: 'lestevez3',
		first_name: 'Linda',
		last_name: 'Estevez',
		profile_image: 'https://robohash.org/idrerumomnis.png?size=50x50&set=set1',
		email: 'lestevez3@goo.gl',
		gender: 'Male',
		city: 'Tonoshō',
		country: 'Japan',
		ethnicity: 'Melanesian',
		cuisine: 'Kiowa food',
		interests: 'Playing Sports',
	},
	{
		id: 5,
		username: 'agriffen4',
		first_name: 'Arleyne',
		last_name: 'Griffen',
		profile_image: 'https://robohash.org/autametquia.png?size=50x50&set=set1',
		email: 'agriffen4@dell.com',
		gender: 'Male',
		city: 'Gobernador Ingeniero Valentín Virasoro',
		country: 'Argentina',
		ethnicity: 'Spaniard',
		cuisine: 'Thai food',
		interests: 'Writing',
	},
	{
		id: 6,
		username: 'hdiem5',
		first_name: 'Hortensia',
		last_name: 'Diem',
		profile_image:
			'https://robohash.org/suntnesciuntqui.png?size=50x50&set=set1',
		email: 'hdiem5@sogou.com',
		gender: 'Male',
		city: 'Poddor’ye',
		country: 'Russia',
		ethnicity: 'Micronesian',
		cuisine: 'Melanesian food',
		interests: 'Cooking',
	},
	{
		id: 7,
		username: 'eatling6',
		first_name: 'Elvina',
		last_name: 'Atling',
		profile_image:
			'https://robohash.org/utcorporisfugiat.png?size=50x50&set=set1',
		email: 'eatling6@oaic.gov.au',
		gender: 'Male',
		city: 'Kuala Lumpur',
		country: 'Malaysia',
		ethnicity: 'Chickasaw',
		cuisine: 'Iroquois food',
		interests: 'Video Games',
	},
	{
		id: 8,
		username: 'rkestian7',
		first_name: 'Raoul',
		last_name: 'Kestian',
		profile_image:
			'https://robohash.org/officiisdelenitidolor.png?size=50x50&set=set1',
		email: 'rkestian7@go.com',
		gender: 'Female',
		city: 'Ubinskoye',
		country: 'Russia',
		ethnicity: 'Puerto Rican',
		cuisine: 'Eskimo food',
		interests: 'Cooking',
	},
	{
		id: 9,
		username: 'fkirsche8',
		first_name: 'Faber',
		last_name: 'Kirsche',
		profile_image:
			'https://robohash.org/estsitexcepturi.png?size=50x50&set=set1',
		email: 'fkirsche8@upenn.edu',
		gender: 'Female',
		city: 'Carauari',
		country: 'Brazil',
		ethnicity: 'White',
		cuisine: 'Native Hawaiian and Other Pacific Islander (NHPI) food',
		interests: 'Cooking',
	},
	{
		id: 10,
		username: 'fgravenor9',
		first_name: 'Filide',
		last_name: 'Gravenor',
		profile_image:
			'https://robohash.org/esseomnisincidunt.png?size=50x50&set=set1',
		email: 'fgravenor9@washingtonpost.com',
		gender: 'Male',
		city: 'Laau',
		country: 'Indonesia',
		ethnicity: 'Thai',
		cuisine: 'Bangladeshi food',
		interests: 'Cooking',
	},
	{
		id: 11,
		username: 'ajoburna',
		first_name: 'Ario',
		last_name: 'Joburn',
		profile_image:
			'https://robohash.org/illoconsequaturquidem.png?size=50x50&set=set1',
		email: 'ajoburna@flavors.me',
		gender: 'Male',
		city: 'Santa Catarina',
		country: 'Portugal',
		ethnicity: 'Pima',
		cuisine: 'Chinese food',
		interests: 'Playing Instruments',
	},
	{
		id: 12,
		username: 'sklynerb',
		first_name: 'Stacy',
		last_name: 'Klyner',
		profile_image:
			'https://robohash.org/nobissuntcorrupti.png?size=50x50&set=set1',
		email: 'sklynerb@multiply.com',
		gender: 'Male',
		city: 'Ust’-Donetskiy',
		country: 'Russia',
		ethnicity: 'Ecuadorian',
		cuisine: 'Micronesian food',
		interests: 'Fishing',
	},
	{
		id: 13,
		username: 'kcaudellc',
		first_name: 'Kameko',
		last_name: 'Caudell',
		profile_image: 'https://robohash.org/rerumautnatus.png?size=50x50&set=set1',
		email: 'kcaudellc@mapy.cz',
		gender: 'Male',
		city: 'Las Varas',
		country: 'Argentina',
		ethnicity: 'Choctaw',
		cuisine: 'Alaskan Athabascan food',
		interests: 'Board Games',
	},
	{
		id: 14,
		username: 'gbrennand',
		first_name: 'Goldarina',
		last_name: 'Brennan',
		profile_image: 'https://robohash.org/autquosearum.png?size=50x50&set=set1',
		email: 'gbrennand@is.gd',
		gender: 'Male',
		city: 'Bagnères-de-Bigorre',
		country: 'France',
		ethnicity: 'Hmong',
		cuisine: 'Central American food',
		interests: 'Playing Sports',
	},
	{
		id: 15,
		username: 'rhavilee',
		first_name: 'Reinaldos',
		last_name: 'Havile',
		profile_image: 'https://robohash.org/ethicipsum.png?size=50x50&set=set1',
		email: 'rhavilee@ocn.ne.jp',
		gender: 'Female',
		city: 'Kizlyar',
		country: 'Russia',
		ethnicity: 'Pakistani',
		cuisine: 'Paraguayan food',
		interests: 'Collecting',
	},
	{
		id: 16,
		username: 'tstoodersf',
		first_name: 'Ty',
		last_name: 'Stooders',
		profile_image:
			'https://robohash.org/nisilaboriosamalias.png?size=50x50&set=set1',
		email: 'tstoodersf@marriott.com',
		gender: 'Female',
		city: 'San Antonio',
		country: 'Mexico',
		ethnicity: 'Spaniard',
		cuisine: 'Shoshone food',
		interests: 'Writing',
	},
	{
		id: 17,
		username: 'ibeminsterg',
		first_name: 'Inessa',
		last_name: 'Beminster',
		profile_image:
			'https://robohash.org/saepecorruptiut.png?size=50x50&set=set1',
		email: 'ibeminsterg@spotify.com',
		gender: 'Male',
		city: 'Redakodi',
		country: 'Indonesia',
		ethnicity: 'Menominee',
		cuisine: 'Yuman food',
		interests: 'Playing Instruments',
	},
	{
		id: 18,
		username: 'smallinderh',
		first_name: 'Sephira',
		last_name: 'Mallinder',
		profile_image:
			'https://robohash.org/rerumeumminima.png?size=50x50&set=set1',
		email: 'smallinderh@altervista.org',
		gender: 'Female',
		city: 'Berlin',
		country: 'Germany',
		ethnicity: 'Ecuadorian',
		cuisine: 'Uruguayan food',
		interests: 'Yoga',
	},
	{
		id: 19,
		username: 'dculbardi',
		first_name: 'Dorrie',
		last_name: 'Culbard',
		profile_image:
			'https://robohash.org/enimrecusandaereprehenderit.png?size=50x50&set=set1',
		email: 'dculbardi@census.gov',
		gender: 'Male',
		city: 'Staryye Atagi',
		country: 'Russia',
		ethnicity: 'Taiwanese',
		cuisine: 'Puerto Rican food',
		interests: 'Video Games',
	},
	{
		id: 20,
		username: 'bleversuchj',
		first_name: 'Brew',
		last_name: 'Leversuch',
		profile_image:
			'https://robohash.org/quiatemporibussit.png?size=50x50&set=set1',
		email: 'bleversuchj@histats.com',
		gender: 'Male',
		city: 'Carrazeda de Ansiães',
		country: 'Portugal',
		ethnicity: 'Alaska Native',
		cuisine: 'Houma food',
		interests: 'Board Games',
	},
];

export const countries = [
	{
		id: 1,
		cuisineName: 'Indonesia',
		ethnicity: 'Indonesian',
		selected: false,
	},
	{
		id: 3,
		cuisineName: 'Germany',
		ethnicity: 'German',
		selected: false,
	},
	{
		id: 5,
		cuisineName: 'Armenia',
		ethnicity: 'Armenian',
		selected: false,
	},
	{
		id: 7,
		cuisineName: 'Norway',
		ethnicity: 'Norwegian',
		selected: false,
	},
	{
		id: 8,
		cuisineName: 'China',
		ethnicity: 'Chinese',
		selected: false,
	},
	{
		id: 11,
		cuisineName: 'Colombia',
		ethnicity: 'Colombian',
		selected: false,
	},
	{
		id: 12,
		cuisineName: 'Brazil',
		ethnicity: 'Brazilian',
		selected: false,
	},
	{
		id: 13,
		cuisineName: 'United States',
		ethnicity: 'American',
		selected: false,
	},
	{
		id: 14,
		cuisineName: 'Saudi Arabia',
		ethnicity: 'Saudi Arabian',
		selected: false,
	},
	{
		id: 16,
		cuisineName: 'Peru',
		ethnicity: 'Peruvian',
		selected: false,
	},
	{
		id: 17,
		cuisineName: 'Vietnam',
		ethnicity: 'Vietnamese',
		selected: false,
	},
	{
		id: 18,
		cuisineName: 'Spain',
		ethnicity: 'Spaniard',
		selected: false,
	},
	{
		id: 20,
		cuisineName: 'Pakistan',
		ethnicity: 'Pakistani',
		selected: false,
	},
	{
		id: 22,
		cuisineName: 'Ecuador',
		ethnicity: 'Ecuadorian',
		selected: false,
	},
	{
		id: 36,
		cuisineName: 'Thailand',
		ethnicity: 'Thai',
		selected: false,
	},
];
